---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: taiga-https-ingress
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`{{ .Values.ingress.host }}`)
      services:
        - name: taiga-gateway-service
          port: 80
  tls:
    secretName: taiga-tls
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: taiga-https-redirect
spec:
  redirectScheme:
    scheme: https
    permanent: true
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: taiga-http-ingress
spec:
  entryPoints:
    - web
  routes:
    - kind: Rule
      match: Host(`{{ .Values.ingress.host }}`) && !PathPrefix(`/.well-known/acme-challenge/`)
      middlewares:
        - name: taiga-https-redirect
      services:
        - name: taiga-gateway-service
          port: 80
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: taiga-tls
spec:
  secretName: taiga-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - {{ .Values.ingress.host }}
