---
apiVersion: v1
kind: Service
metadata:
  name: taiga-back-service
spec:
  selector:
    app: taiga-back
  ports:
  - port: 8000
    targetPort: 8000
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: taiga-front-service
spec:
  selector:
    app: taiga-front
  ports:
  - port: 80
    targetPort: 80
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: taiga-events-service
spec:
  selector:
    app: taiga-events
  ports:
  - port: 8888
    targetPort: 8888
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: taiga-protected-service
spec:
  selector:
    app: taiga-protected
  ports:
  - port: 8003
    targetPort: 8003
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: taiga-gateway-service
spec:
  selector:
    app: taiga-gateway
  ports:
  - port: 80
    targetPort: 80
  type: ClusterIP
