apiVersion: v1
kind: ConfigMap
metadata:
  name: taiga-gateway-config
data:
  default.conf: |
    server {
        listen 80 default_server;

        client_max_body_size 100M;
        charset utf-8;

        location / {
            proxy_pass http://taiga-front-service:80/;
            proxy_pass_header Server;
            proxy_set_header Host $http_host;
            proxy_redirect off;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Scheme $scheme;
        }

        location /api/ {
            proxy_pass http://taiga-back-service:8000/api/;
            proxy_pass_header Server;
            proxy_set_header Host $http_host;
            proxy_redirect off;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Scheme $scheme;
        }

        location /admin/ {
            proxy_pass http://taiga-back-service:8000/admin/;
            proxy_pass_header Server;
            proxy_set_header Host $http_host;
            proxy_redirect off;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Scheme $scheme;
        }

        location /static/ {
            alias /taiga/static/;
        }

        location /_protected/ {
            internal;
            alias /taiga/media/;
            add_header Content-disposition "attachment";
        }

        location /media/ {
            proxy_pass http://taiga-protected-service:8003/;
            proxy_pass_header Server;
            proxy_set_header Host $http_host;
            proxy_redirect off;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Scheme $scheme;
        }

        location /events {
            proxy_pass http://taiga-events-service:8888/events;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            proxy_set_header Host $host;
            proxy_connect_timeout 7d;
            proxy_send_timeout 7d;
            proxy_read_timeout 7d;
        }
    }
