apiVersion: apps/v1
kind: Deployment
metadata:
  name: taiga-events
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: taiga-events
  template:
    metadata:
      labels:
        app: taiga-events
    spec:
      containers:
      - name: taiga-events
        image: {{ .Values.image.events.name }}:{{ .Values.image.events.tag }}
        imagePullPolicy: Always
        ports:
        - containerPort: 8888
        envFrom:
        - secretRef:
            name: taiga-events-secret
        resources:
          requests:
            memory: "128Mi"
            cpu: "50m"
          limits:
            memory: "256Mi"
            cpu: "500m"
